
## Set the working directory

```{r}
getwd()
setwd(""../data")
getwd()
```

## Install useful packages 

```{r}
library(tidyverse)
library(lubridate)
library(dplyr)
```

## Import your csv. data

```{r}
data <- read.csv("timeseries_selectedcities1.csv")
head(data)
```

## Rename column headings

```{r}
names(data) <- c("Country","City","Date","Mobility_Retail","Mobility_Transit","Mobility_Workplace","Mobility_Residential","Response_Stringency")
colnames(data)
```

## Working and filtering by dates

```{r}
data$Date <- as.Date(data$Date)
str(data)
```

```{r}
data_bydate <- filter(data, between(Date, as.Date("2020-02-15"), as.Date("2020-04-01")))
head(data_bydate)
```

## Time series plot of mobility

```{r}
shade_select <- data_bydate %>% dplyr::select(City, Date, Response_Stringency)
shade_select <- shade_select %>% dplyr::filter(!is.na(Response_Stringency))
shade_select <- shade_select %>% mutate(end = lead(Date))
shade_select$end[is.na(shade_select$end)] <- as.Date("2020-04-01", origin="1970-01-01")
shade_select <- shade_select %>% rename("start" = "Date")
shade_select$y1 = -Inf
shade_select$y2 =  Inf

data_bydate$City = factor(data_bydate$City, levels=c("Wuhan", "Beijing", "Shanghai", 
            "Tokyo", "New York", "Los Angeles", 
            "Hong Kong", "Singapore", "Ho Chi Minh City",
            "Paris", "Mumbai", "Delhi",
            "Milan", "Manila", "Barcelona", "Madrid",
            "London", "Stockholm","Brussels", "Al Ahmadi",
            "Dublin", "Doha", "Riyadh",
            "Lima", "La Paz", "Ulaanbaatar",
            "Istanbul"))

mobility_selectdates <- ggplot(data_bydate)+
  geom_line(aes(x=Date, y=Mobility_Workplace),size = 1.3, lineend="round", linejoin="round", color="#74787b")+
  geom_line(aes(x=Date, y=Mobility_Residential),size = 1.3, lineend="round", linejoin="round", color="#000000")+
  geom_rect(data = shade_select, ymin = -Inf, ymax = Inf, aes(NULL, NULL, xmin = start, xmax = end, fill = Response_Stringency), alpha = .4)+
  scale_fill_gradientn(colours=(brewer.pal(n=9,"YlOrRd")), limits=c(0, 100))+
  facet_wrap(~City)+
  labs(title="Mobility: Workplace and residential", y="Change in mobility (%)", x="Date 2020")+
  labs(fill = "Stringency of response")+
  theme_classic() +
  theme(text = element_text(size = 15), axis.title.x = element_blank(), axis.text.x = element_text(angle = 90),
        strip.background = element_rect(colour = "white", fill = "white"),
        legend.title = element_text( size = 14, color = "black"), 
        legend.position = "bottom",legend.box = "horizontal")
mobility_selectdates
```

## Export it as a high resolution tiff image

```{r}
tiff("mobility_ylorrd.tiff", units= "in", width = 11, height = 11, res=300)
plot(mobility_selectdates)
dev.off()
```
